
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uspqgeozxmfmingjasro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzcHFnZW96eG1mbWluZ2phc3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMzMxOTYsImV4cCI6MjA1NjYwOTE5Nn0.MHVHyZ7PP5fbFcSRJm7XHHLgdsDUlEJ6pBusetfXoGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Export the URL and keys as constants so they can be used elsewhere
export const SUPABASE_API_URL = SUPABASE_URL;
export const SUPABASE_ANON_KEY = SUPABASE_PUBLISHABLE_KEY;

// Create and export the client with proper typing
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Export the Supabase key for authentication in fetch calls
export const supabaseKey = SUPABASE_PUBLISHABLE_KEY;
